name: veegify
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.3+7

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  pin_code_fields: ^8.0.1
  provider: ^6.1.5
  font_awesome_flutter: ^10.8.0
  share_plus: ^11.0.0
  http: ^1.4.0
  shared_preferences: ^2.5.3
  fluttertoast: ^8.2.12
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  url_launcher: ^6.3.1
  carousel_slider: ^5.1.1
  google_places_flutter: ^2.1.0
  google_fonts: ^6.3.0
  qr_flutter: ^4.1.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  image_picker: ^1.2.0
  speech_to_text: ^7.3.0
  permission_handler: ^12.0.1
  video_player: ^2.10.0
  email_validator: ^3.0.0
  google_maps_flutter: ^2.14.0
  flutter_polyline_points: ^3.1.0
  socket_io_client: ^3.1.2
  razorpay_flutter: ^1.4.0
  path_provider: ^2.1.0
  open_filex: ^4.5.0
  flutter_html_to_pdf: ^0.7.0
  printing: ^5.14.2
  pdf: ^3.11.3
  lottie: ^3.3.1
  flutter_easyloading: ^3.0.5
  package_info_plus: ^8.3.1
  new_version_plus: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/scooter.png
    - assets/images/signup.png
    - assets/images/login.png
    - assets/images/otp.png
    - assets/images/dosa.png
    - assets/images/refer.png
    - assets/images/password.png
    - assets/images/applogo.png
    - assets/images/logolocation.png
    - assets/videos/home.mp4
    - assets/images/logo.png
    - assets/images/no food.png
    - assets/images/check_mark.png
    - assets/images/map_placeholder.png
    - assets/images/rider.png
    - assets/images/destination.png
    - assets/images/wattsapp.png
    - assets/lottie/food_preparing.json

# <-- IMPORTANT: flutter_icons must be a top-level key (not under flutter:)
flutter_icons:
  android: true
  ios: true
  image_path: "assets/appstore.png"
  remove_alpha_ios: true
